stages:
    - build
    - push
    - clean
    - deploy

before_script:
    - docker --version
    - docker-compose --version

build:
    stage: build
    script:
        - docker build --pull -t gitlab-runner-docker:$CI_PIPELINE_ID .

push:
    stage: push
    only:
        - master
    script:
        - docker tag gitlab-runner-docker:$CI_PIPELINE_ID ${REGISTRY}/gitlab-runner-docker
        - docker push ${REGISTRY}/gitlab-runner-docker

clean:
    stage: clean
    script:
        - docker rmi -f gitlab-runner-docker:$CI_PIPELINE_ID

deploy:
    stage: deploy
    script:
        - echo Deploying production on ${PROD_HOST}...
        - docker -H ${PROD_HOST} service update --force --detach ${PROD_SERVICE_NAME}
    only:
        - master
