stages:
    - build
    - push
    - clean

before_script:
    - docker --version
    - docker-compose --version

build:
    stage: build
    script:
        - docker build --pull -t gitlab-runner-docker:$CI_PIPELINE_ID .

push:
    stage: push
    only:
        - master
    script:
        - docker tag gitlab-runner-docker:$CI_PIPELINE_ID ${REGISTRY}/gitlab-runner-docker
        - docker push ${REGISTRY}/gitlab-runner-docker

clean:
    stage: clean
    script:
        - docker rmi -f gitlab-runner-docker:$CI_PIPELINE_ID
