stages:
    - build
    - push
    - deploy
    - clean

before_script:
    - docker --version
    - docker-compose --version

build:
    stage: build
    script:
        - docker build --pull --no-cache -t gitlab-runner-docker:${CI_COMMIT_SHORT_SHA} .

push:
    stage: push
    only:
        - master
    script:
        - docker tag gitlab-runner-docker:${CI_COMMIT_SHORT_SHA} ${REGISTRY}/gitlab-runner-docker:${CI_COMMIT_SHORT_SHA}
        - docker push ${REGISTRY}/gitlab-runner-docker:${CI_COMMIT_SHORT_SHA}

temporary:
    stage: clean
    script:
        - docker rmi -f gitlab-runner-docker:${CI_COMMIT_SHORT_SHA}

registry:
    stage: clean
    only:
        - master
    script:
        - docker rmi -f ${REGISTRY}/gitlab-runner-docker:${CI_COMMIT_SHORT_SHA}

deploy:
    stage: deploy
    script:
        - echo Deploying production on ${PROD_HOST}...
        - docker -H ${PROD_HOST} service update --force --detach --image=${REGISTRY}/gitlab-runner-docker:${CI_COMMIT_SHORT_SHA} ${PROD_SERVICE_NAME}
    only:
        - master
